# Wandb Sweep Configuration for AlphaZero Clique n7k4
# Architecture: 32_8 (fixed)
program: src/pipeline_clique.py
project: alphazero_clique-src
entity: asoibelman-institut-des-hautes-tudes-scientifiques-ihes
method: bayes
metric:
  goal: minimize
  name: validation_policy_loss
early_terminate:
  type: hyperband
  min_iter: 5
  eta: 2
  s: 3

parameters:
  # Fixed architecture parameters
  mode:
    value: "pipeline"
  vertices:
    value: 7
  k:
    value: 4
  hidden-dim:
    value: 32
  num-layers:
    value: 8
  perspective-mode:
    value: "alternating"
  game-mode:
    value: "symmetric"
  iterations:
    value: 20
  num-cpus:
    value: 6
  eval-threshold:
    value: 0.45
  num-games:
    value: 21
  lr-threshold:
    value: 0.001
  min-lr:
    value: 0.0000001
  value-weight:
    value: 1.0
  min-alpha:
    value: 0.5
  max-alpha:
    value: 100.0
  
  # Optimization targets - main sweep parameters
  initial-lr:
    distribution: log_uniform_values
    min: 0.0001
    max: 0.002
  
  batch-size:
    values: [16, 32, 64, 96]
  
  epochs:
    min: 10
    max: 30
  
  self-play-games:
    min: 60
    max: 150
  
  mcts-sims:
    values: [200, 300, 400, 600, 800]
  
  skill-variation:
    min: 0.2
    max: 0.8
  
  # Learning rate schedule parameters
  lr-factor:
    values: [0.5, 0.7, 0.85]
  
  lr-patience:
    values: [3, 5, 7]